services:
  db:
    image: postgres:16
    container_name: jetmenu_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jetmenu
      POSTGRES_PASSWORD: jetmenu
      POSTGRES_DB: jetmenu_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
